import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "../styles/index.css"
import { Headers } from '@/components/Headers/Headers'
import Footer from '@/components/Footer/Footer'
import { NextAuthProvider } from '@/providers/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MT Gold',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <NextAuthProvider>
          <Headers />
          <div className='flex flex-col flex-1 min-h-screen'>
            {children}
          </div>
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  )
}
